version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitespeed-api
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
